### ISSUE TITLE
Coupling in omc3

### ISSUE THREAD

**Issue by awegsche** [pylhc/omc3#30]
Coupling codes have to be rewritten in python3. Related to #13 

- [ ] plus a few bugfixes
- [ ] nice, clean stuff
- [ ] have to understand Ryoichi's black box
- [ ] ADT, is the different position of hor and ver kickers a problem?
- [ ] write tests

**Comment by JoschD** [comment]
Take care of measure_optics.py line 51:

``if measure_input.only_coupling: break``

**Comment by awegsche** [comment]
Coupling is now added to omc3

### TODOs 
- [ ] averaging of input data
- [ ] averaging of constructed phases
- [ ] use the two above to propagate errors
- [ ] **compensation**

### Next Step:
Benchmark compensation methods:

- denominator
- Ryoichi ([paper](https://accelconf.web.cern.ch/IPAC2011/papers/WEPC030.PDF))
- Felix

**Comment by JoschD** [comment]
Any updates on the points here? @awegsche

**Comment by fsoubelet** [comment]
tracking this in #532
