### ISSUE TITLE
Fix GUI issues

### ISSUE THREAD

**Issue by JoschD** [pylhc/omc3#327]
Major:
-------
- [ ] ~Beta from amplitude is giving strange values and also NaN which in turn prevents normalized dispersion from being calculated (BBS) https://gitlab.cern.ch/acc-co/lhc/lhc-app-beta-beating/-/issues/178~
- [ ] Bug in TFS reader (OMC3, BBS): https://gitlab.cern.ch/acc-co/lhc/lhc-app-beta-beating/-/issues/179
- [ ] Add DPP to table (OMC3): https://gitlab.cern.ch/acc-co/lhc/lhc-app-beta-beating/-/issues/203
- [ ] ~Getdiff, used to evaluate corrections, does not work in (BBS)~
- [x] Generate b2 errors for beam 2 arc dipoles
- [ ] ~Re-Analysis not working (BBS): https://its.cern.ch/jira/browse/BBGUI-167~
- [x] Move b2 errors from omc-workspace (OMC3, BBS): https://gitlab.cern.ch/acc-co/lhc/lhc-app-beta-beating/-/issues/185 (only blocking when any user reading rights are removed)

Other:
-------
- [x] Extract MQTs (OMC3): https://its.cern.ch/jira/projects/BBGUI/issues/BBGUI-165
- [x] Add debug flag set in settings to be passed on to omc3 (very helpful for finding issues, OMC3): https://its.cern.ch/jira/projects/BBGUI/issues/BBGUI-160
- [x] Add Amplitude Detuning analysis python call (OMC3): https://its.cern.ch/jira/projects/BBGUI/issues/BBGUI-169
- [x] Fix Nattune updater (OMC3): https://its.cern.ch/jira/projects/BBGUI/issues/BBGUI-170
- [x] Implement defaults (OMC3): https://its.cern.ch/jira/projects/BBGUI/issues/BBGUI-173

**Comment by JoschD** [comment]
The remaining Question is: Why are there `inf` values in the RDT-errors in the first place?

**Comment by fsoubelet** [comment]
Chiming in: I don't think we really want to invest resources into fixing BBS-exclusive GUI issues.

**Comment by JoschD** [comment]
of course not. but some of them are OMC3
